CREATE TABLE IF NOT EXISTS CUSTOMER (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(225) NOT NULL,
    email VARCHAR(225) NOT NULL,
    first_name VARCHAR(225),
    last_name VARCHAR(225),
    active INT NOT NULL
    );

INSERT INTO CUSTOMER (username, email, first_name, last_name, active) VALUES
        ('user1', 'user1@gmail.com', 'user1', 'admin1', 1),
        ('user2', 'user2@gmail.com', 'user2', 'admin2', 1),
		('user3', 'user3@gmail.com', 'user3', 'admin3', 1),
        ('user4', 'user4@gmail.com', 'user4', 'admin4', 1);
